//Problem:
/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 		1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do
 * not exceed four million, find the sum of the even-valued terms.
 */
//Answer: 	4613732

public class Problem_002 {
	
	public static String work(){
		final int MAX = 4000000;
		int num1 = 1, num2 = 2, sum = 0;
		int temp;
		String results = "hello";
		
		while (num1 < MAX && num2 < MAX) {
			if (num2 % 2 == 0)
				sum += num2;
			
			temp = num1 + num2;
			num1 = num2;
			num2 = temp;
		}
		
		results = Integer.toString(sum);
		return results;
	}
}
